funcei/app/Http/routes.php
<?php

	Route::get('/', 'HomeController@index');





//---------------------------------------------------------------
// Admin
//---------------------------------------------------------------
	Route::get('admin',array( 'as' => 'admin' , 'uses' => 'AdminController@admin'));
	Route::get('admin/{modulo}',array( 'as' => 'modulo' , 'uses' => 'AdminController@modulo'));

	Route::get('admin/{modulo}/subcategorias',array( 'as' => 'modulo_subcategoria' , 'uses' => 'AdminController@moduloSubcategoria'));

	// get Alta Subcategoria
	Route::get('admin/{modulo}/subcategoria/crear',array( 'as' => 'alta_subcategoria' , 'uses' => 'SubcategoriaController@getAltaRegistro'));
	// get Modificacion Subcategoria
	Route::get('admin/{modulo}/subcategoria/{registro}/editar',array( 'as' => 'modificacion_subcategoria' , 'uses' => 'SubcategoriaController@getModificacionRegistro'));

	// get Alta
	Route::get('admin/{modulo}/{gestor}/crear',array( 'as' => 'alta_registro' , 'uses' => 'AdminController@getAltaRegistro'));
	// get Modificacion
	Route::get('admin/{modulo}/{gestor}/{tabla}/{registro}/editar',array( 'as' => 'modificacion_registro' , 'uses' => 'AdminController@getModificacionRegistro'));


//---------------------------------------------------------------
// API Admin (ponerle seguridad, identificacion requerida)
//---------------------------------------------------------------

	// REST API ( sirve para el Jquery )
	Route::group(array('prefix' => 'api', 'before' => 'auth.admin' ), function() {
		// Sirve para hacer route('api')
		Route::get('/', array('as' => 'api'));

		Route::post('file/upload', array('as' => 'api_file_upload', 'uses' => 'FileController@upload'));
		Route::post('file/delete', array('as' => 'api_file_delete', 'uses' => 'FileController@delete'));

		// do Alta
		Route::post('api/alta/{modulo}/{gestor}/{tabla}',array( 'as' => 'api_alta_registro' , 'uses' => 'AdminController@doAltaRegistro'));
		// do Modificacion
		Route::post('api/{modulo}/{gestor}/{tabla}/{registro}/editar',array( 'as' => 'api_modificacion_registro' , 'uses' => 'AdminController@doModificacionRegistro'));

		//Route::get('modelo/subcategoria/gestor/{id_gestor}', array('as' => 'api_subcategorias_de_gestor', 'uses' => 'SubcategoriaController@getSubcategoriasGestor'));
		//Route::resource('modelo/{modelo}/{condicion_campo}/{condicion_valor}', 'ApiController',
		Route::resource('gestor', 'GestorController',
			['only' => ['index', 'store', 'update', 'destroy', 'show']]);

	});

	// do Alta Subcategoria
	Route::post('api/{modulo}/subcategoria/crear',array( 'as' => 'do_alta_subcategoria' , 'uses' => 'SubcategoriaController@doAltaRegistro'));
	// do Modificacion Subcategoria
	Route::post('api/{modulo}/subcategoria/{registro}/editar',array( 'as' => 'do_modificacion_subcategoria' , 'uses' => 'SubcategoriaController@doModificacionRegistro'));
	// do Eliminar Subcategoria
	Route::get('api/{modulo}/subcategoria/{registro}/eliminar',array( 'uses' => 'SubcategoriaController@doEliminacionRegistro'));

	// do Alta
	Route::post('api/{modulo}/{gestor}/{tabla}/crear',array( 'as' => 'do_alta_registro' , 'uses' => 'AdminController@doAltaRegistro'));
	// do Modificacion
	Route::post('api/{modulo}/{gestor}/{tabla}/{registro}/editar',array( 'as' => 'do_modificacion_registro' , 'uses' => 'AdminController@doModificacionRegistro'));
	// do Eliminar
	Route::get('api/{modulo}/{gestor}/{tabla}/{registro}/eliminar',array( 'uses' => 'AdminController@doEliminacionRegistro'));
	// do Mover
	Route::get('api/{modulo}/{gestor}/{tabla}/{registro}/{direccion}/mover',array( 'as' => 'do_mover_registro', 'uses' => 'AdminController@doMoverRegistro'));
	// do Activar/Desactivar
	Route::get('api/{modulo}/{gestor}/{tabla}/{registro}/{activar}/activar',array( 'as' => 'do_activar_registro', 'uses' => 'AdminController@doActivarRegistro'));




	//Estaticos

	Route::get('/upload/{tabla}/{field}/{file}',array( 'as' => 'upload' ));

	Route::get('/upload/{tabla}/{field}',array( 'as' => 'upload_table' ));









//---------------------------------------------------------------
// Sitio	{modulo} / {gestor} / {subcategoria} / {publicacion_slug}
//---------------------------------------------------------------

	Route::get('{modulo}/{gestor}/{subcategoria}/{id_subcategoria}', array( 'as' => 'listado_publicaciones' , 'uses' => 'HomeController@getAllPublicaciones'));

	Route::get('{modulo}/{gestor}/{subcategoria}/{id_subcategoria}/{articulo}/{id_articulo}', array( 'as' => 'publicacion' , 'uses' => 'HomeController@getPublicacion'));

	Route::get('contacto', array( 'as' => 'estatico_contacto' , 'uses' => 'EstaticoController@getContacto'));

	Route::post('contacto', array( 'as' => 'enviar_email' , 'uses' => 'EstaticoController@doContacto'));


//---------------------------------------------------------------
// Errores
//---------------------------------------------------------------
Route::get('archivo_inexistente', array( 'as' => 'no_file' , 'uses' => 'ErrorController@getNoFile'));

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

funcei/resources/views/admin/admin.blade.php
@extends('app')

@section('admin_content')

@include('includes.admin_breadcrumb')

<div class="row">

	@include ('admin.sidebar')

	@if( ISSET($moduloActual))
		<div class="col-sm-10 col-md-10 col-md-offset-1 main">

			<div class="container">
				<div class="row">
					<div class="col-md-11 col-md-offset-1">
						<h2>{{ $moduloActual['nombre'] }}</h2>
						<a class="btn btn-primary" href="{{ route('modulo_subcategoria',array($moduloActual['id']))}}">Subcategorias</a>
					</div>
				</div>
			</div>

			@if( isset($moduloActual) && isset($moduloActual['gestores']) )
			@foreach( $moduloActual['gestores'] as $g )
			<div class="container">
				<div class="row">
					<div class="col-md-11 col-md-offset-1">
								<div class="ibox float-e-margins">
								    <div class="ibox-title">
								        <h5>{{ $g['nombre'] }}</h5>
								        <div class="ibox-tools">
														@if( count($g['campos']) == 0 )
														<div class="alert alert-danger" role="alert"> No tiene campos definidos. </div>
														@else
														<a class="btn btn-primary" href="{{ route('alta_registro',array($moduloActual['id'], $g['id'])) }}">Publicar</a>
														@endif
								            <a class="collapse-link">
								                <i class="fa fa-chevron-up"></i>
								            </a>
								        </div>
								    </div>
								    <div class="ibox-content">

								        <!--<table class="table">-->
									<table class="table table-striped">
									<thead>
										<tr>
											<th>#</th>
											@if( count($g['data']) )
												@foreach( $g['campos'] as $c )
													@if( $c['visible_en_listado'] )
														<th>{{ $c['nombre'] }}</th>
													@endif
												@endforeach
												<th>Ordenar</th>
												<th>Opciones</th>
											@endif

										</tr>
									</thead>
									<tbody>
									@if( count($g['data']) )
										@foreach( $g['data'] as $i => $data )
											@if( ( $g['custom'] ||  $data->id_gestor == $g['id'] ) )
												<tr>
													<th>{{ $i+1 }}</th>
													@foreach( $g['campos'] as $c )

														@if( $c['visible_en_listado'] )
															@if( isset($data->$c['nombre']) )
																@if( $c['tipo'] == 'file' )
																	 @if( count($data->$c['nombre']) > 1 )
																	 	<td>
																	 		<div class="jFiler-items-default"><div class="jFiler-item"><div class="jFiler-item-icon"><i class="icon-jfi-file-o jfi-file-type-application jfi-file-ext-img"></i></div><div><div>
																			{{ count($data->$c['nombre']) }} archivos.
																		</td>
																	 @else
																		@if( ISSET($data->{'type_'.$c['nombre']}))
																			@if( $data->{'type_'.$c['nombre']} == 'jpg' || $data->{'type_'.$c['nombre']} == 'jpeg' || $data->{'type_'.$c['nombre']} == 'png' || $data->{'type_'.$c['nombre']} == 'gif')

																				<td><img src="{{ asset( 'upload/' . $g['contenido'] . '/' . $c['nombre'] . '/' . $data->$c['nombre'] ) }}" alt="preview" width="60" height="60" /></td>
																			@else
																				<td>
																					<div class="jFiler-items-default"><div class="jFiler-item"><div class="jFiler-item-icon"><i class="icon-jfi-file-o jfi-file-type-application jfi-file-ext-img"></i></div><div><div>
																					{{ $data->{'type_'.$c['nombre']} }}
																				</td>
																			@endif
																		@else
																			<td class="alert alert-warning" ><em>No hay archivos.</em></td>
																		@endif
																	@endif
																@else
																	<td>{{ str_limit($data->$c['nombre'], 220) }}</td>
																@endif
															@else
																<td class="alert alert-danger" >No existe campo <b>{{$c['nombre']}}</b></td>
															@endif
														@endif
													@endforeach
													<td>
														@if( $i > 0 )
															<a title="Mover hacia arriba" href="{{ route('do_mover_registro',array($moduloActual['id'], $g['id'], $g['contenido'], $data->id, 0)) }}"><em class="glyphicon glyphicon-chevron-up"></em></a> |
														@else
															<em class="glyphicon glyphicon-chevron-up"></em> |
														@endif
														@if( $i < count($g['data'])-1 )
															<a title="Mover hacia abajo" href="{{ route('do_mover_registro',array($moduloActual['id'], $g['id'], $g['contenido'], $data->id, 1)) }}"><em class="glyphicon glyphicon-chevron-down"></em></a>
														@else
															<em class="glyphicon glyphicon-chevron-down"></em>
														@endif
													</td>
													<td>
														<a href="{{ route('modificacion_registro',array($moduloActual['id'], $g['id'], $g['contenido'], $data->id)) }}" title="Editar"><em class="glyphicon glyphicon-pencil"></em></a> |
														<a href="#" title="Eliminar" data-toggle="modal" class="btn_eliminar"
															data-target="#modalEliminar"
															data-modulo="{{ $moduloActual['id'] }}"
															data-gestor-id="{{ $g['id'] }}"
															data-gestor-contenido="{{ $g['contenido'] }}"
															data-id="{{ $data->id }}">
															<em class="glyphicon glyphicon-trash"></em>
														</a> |
														@if( $data->activo )
															<a title="Activado" href="{{ route('do_activar_registro',array($moduloActual['id'], $g['id'], $g['contenido'], $data->id, 0)) }}"><em class="glyphicon glyphicon-eye-open"></em></a>
														@else
															<a class="llamativo" title="Desactivado" href="{{ route('do_activar_registro',array($moduloActual['id'], $g['id'], $g['contenido'], $data->id, 1)) }}"><em class="glyphicon glyphicon-eye-close"></em></a>
														@endif
													</td>
												</tr>
											@endif
										@endforeach
									@else
										<tr>
											<td> No hay contenido cargado.</td>
										</tr>
									@endif
									</tbody>
								</table>

							</div>
						</div>
					</div>
				</div>
			</div>
			@endforeach
		@endif

	@endif
</div>

@include ('includes.modal_eliminar')

@endsection

funcei/resources/views/admin/admin_subcategoria.blade.php
@extends('app')

@section('admin_content')

<div class="row">
	<div class="col-sm-3 col-md-2 col-md-offset-3">
		<ol class="breadcrumb">
		    <li>
		        <a href="/admin">Admin</a>
		    </li>
				@if( isset($moduloActual) )
					<li>
		        	<a href="{{ route('admin', array($moduloActual['id'])) }}">{{ $moduloActual['nombre'] }}</a>
		    	</li>
		    	<li class="active">
		        	<strong>Subcategorias</strong>
		    	</li>
				@endif
		</ol>
	</div>
</div>

<div class="row">

	@include ('admin.sidebar')

	<div class="col-sm-10 col-md-10 col-md-offset-1 main">

		@if( ISSET($categorias) )


		<div class="container">
			<div class="row">
				<div class="col-md-11 col-md-offset-1">
					<h2>Subcategorias</h2>
				</div>
			</div>
		</div>

		<!-- Categoria -->
		<div class="container">
			<div class="row">
				<div class="col-md-11 col-md-offset-1">


					<div class="ibox float-e-margins">
					    <div class="ibox-title">

					        <div class="ibox-tools">
											<a class="btn btn-primary" href="{{ route('alta_subcategoria',array($moduloActual['id'])) }}">Agregar</a>
					            <a class="collapse-link">
					                <i class="fa fa-chevron-up"></i>
					            </a>
					        </div>
					    </div>
					    <div class="ibox-content">

					        <!--<table class="table">-->
								<table class="table table-striped">
									<thead>
										<tr>
											<th>#</th>
											<th>Subcategoria</th>
											<th>Categoria</th>
											<th>Opciones</th>
										</tr>
									</thead>

									<tbody>
									@foreach( $categorias as $cat )
										@if( count($cat->subcategorias) )
											@foreach( $cat->subcategorias as $s )
												<tr>
													<th>{{ $s->id }}</th>
													<td>{{ $s->nombre }}</td>
													<td>{{ $cat->nombre }}</td>
													<td>
														<a href="{{ route('modificacion_subcategoria',array($moduloActual['id'], $s->id)) }}">Editar</a> |
														<a href="#" data-toggle="modal" class="btn_eliminar_subcategoria"
															data-target="#modalEliminar"
															data-modulo="{{ $moduloActual['id'] }}"
															data-id="{{ $s->id }}">
															Eliminar
														</a>
													</td>
												</tr>
											@endforeach
										@else
											<tr>
												<td> No hay contenido cargado.</td>
											</tr>
										@endif
									@endforeach
									</tbody>
								</table>
							</div>
					</div>

					@if( isset($moduloActual) )
						<a type="button" class="btn btn-default" href="{{ route('modulo', array($moduloActual['id'])) }}">Volver</a>
					@endif
				</div>
			</div>
		</div>
		<!-- Fin:Categoria -->
		@endif

</div>

@include ('includes.modal_eliminar')

@endsection

funcei/resources/views/admin/alta.blade.php
@extends('app')

@section('admin_content')

<div class="row">

	@include('includes.admin_breadcrumb', array('accion' => 'publicar nueva'))

	@include ('admin.sidebar')
	<div class="col-sm-offset-2 col-md-offset-2 col-sm-7 col-md-8 main">

    <h2>{{ $gestor->nombre }}</h2>
    <!-- FORM -->
    <form class="form-horizontal row" id="form_abm" method="POST" action="{{ route('do_alta_registro',array($id_modulo, $gestor->id, $gestor->contenido)) }}" enctype="multipart/form-data">

			@include ('admin.fields_static_alta')

			@include ('admin.fields')

    </form>
    <!-- END FORM -->

  </div>

</div>

@endsection

funcei/resources/views/admin/alta_subcategoria.blade.php
@extends('app')

@section('admin_content')

<div class="row">

	@include('includes.admin_subcategoria_breadcrumb', array('accion' => 'agregar nueva'))

	<div class="col-sm-3 col-md-2 sidebar">
		@if( $modulos )
		<ul class="nav nav-sidebar">
			@foreach( $modulos as $m )
			<li><a href="{{ route('admin') }}/{{ $m->id }}">{{ $m->nombre }}</a></li>
			@endforeach
		</ul>
		@endif
	</div>
	<div class="col-sm-offset-2 col-md-offset-2 col-sm-7 col-md-8 main">

    <h2>Sub-categorias</h2>
    <!-- FORM -->
    <form class="form-horizontal row" method="POST" action="{{ route('do_alta_subcategoria',array($id_modulo)) }}">

			<!-- CATEGORIA (GESTOR) -->
			<div class="form-group">
				<label for="id_gestor" class="col-sm-2 control-label">Categoria</label>
				<div class="col-sm-10">
					<select class="form-control" name="id_gestor" id="id_gestor">
						@foreach( $categorias as $categoria )
							<option value="{{ $categoria->id }}">{{ $categoria->nombre }}</option>
						@endforeach
					</select>
				</div>
			</div>

      <!-- TEXT -->
      <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Nombre</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="nombre" name="nombre">
        </div>
      </div>


      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">Agregar</button>
          <a class="btn btn-default" href="{{ route('modulo_subcategoria',$id_modulo) }}">Volver</a>
        </div>
      </div>

      <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />

    </form>
    <!-- END FORM -->


  </div>

</div>

@endsection

funcei/resources/views/admin/fields.blade.php
@foreach( $gestor->campos as $c )

	@if( $c->tipo == 'text' )
		<!-- TEXT -->
		<div class="form-group">
			<label for="{{ $c->nombre }}" class="col-sm-2 control-label">{{ $c->nombre }}</label>
			<div class="col-sm-10">
				<input type="text" class="form-control" id="{{ $c->nombre }}" name="{{ $c->nombre }}"
				@if( ISSET($registro) )
					value="{{ $registro->{$c->nombre} }}"
				@endif
				>
			</div>
		</div>
	@elseif( $c->tipo == 'textarea' )
		<!-- TEXTAREA -->
		<div class="form-group">
			<label for="{{ $c->nombre }}" class="col-sm-2 control-label">{{ $c->nombre }}</label>
			<div class="col-sm-10">
				<textarea class="form-control" rows="3" id="{{ $c->nombre }}" name="{{ $c->nombre }}" >@if( ISSET($registro) ) {{ $registro->{$c->nombre} }}@endif</textarea>
			</div>
		</div>

	@elseif( $c->tipo == 'checkbox' )
		<!-- CHECKBOX (falta modificacion) -->
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<div class="checkbox">
					<label>
						<input type="checkbox" input="{{ $c->nombre }}" name="{{ $c->nombre }}" value="1"
						@if( ISSET($registro) && $registro->{ $c->nombre } == 1 )
							checked="checked"
						@endif
						> {{ $c->nombre }}
					</label>
				</div>
			</div>
		</div>

	@elseif( $c->tipo == 'radio' )
		<!-- RADIO (ES UTIL?)(falta modificacion) -->
		<div class="form-group">
			<div class="radio col-sm-offset-2 col-sm-10">
				<label>
					<input type="radio" id="{{ $c->nombre }}" name="{{ $c->nombre }}" value="1">
					{{ $c->nombre }}
				</label>
			</div>
		</div>

	@elseif( $c->tipo == 'select' )
		<!-- falta modificacion -->
		@if( ISSET($c->opciones) )
			<!-- SELECT -->
			<div class="form-group">
				<label for="{{ $c->nombre }}" class="col-sm-2 control-label">{{ $c->nombre }}</label>
				<div class="col-sm-10">
					<select class="form-control" name="{{ $c->nombre }}" id="{{ $c->nombre }}">
						@foreach( $c->opciones as $o)
							<option value="{{ $o }}">{{ $o }}</option>
						@endforeach
					</select>
				</div>
			</div>
		@else
			<div class="form-group">
				<label for="{{ $c->nombre }}" class="col-sm-2 control-label">{{ $c->nombre }}</label>
				<div class="col-sm-10">
					<div class="alert alert-danger" role="alert"> Select: campo "opciones" esta vacío. </div>
				</div>
			</div>
		@endif
	@elseif( $c->tipo == 'file' )
		<div class="form-group">
			<label for="{{ $c->nombre }}" class="col-sm-2 control-label">{{ $c->nombre }}</label>
			<div class="col-sm-10">
				<div class="dropzone" id="{{ $c->nombre }}">
				</div>
			</div>
		</div>
		{{--
		<!--Subir 1 solo file-->
			<!-- BORRA IMG ANTERIOR -->
			<!--<input type="hidden" name="borra_{{ $c->nombre }}" value="{{ $registro->{$c->nombre} }}">-->
		<!-- FILE -->
		<!--<div class="form-group">
			<label for="inputEmail3" class="col-sm-2 control-label">{{ $c->nombre }}</label>
			<div class="col-sm-10">
				<div class="jFiler jFiler-theme-default">
					<input type="file" name="{{ $c->nombre }}[]" id="{{ $c->nombre }}" multiple="multiple"/>
				</div>
			</div>
		</div>-->
		--}}

	@elseif( $c->tipo == 'hidden' )
		<input type="hidden" name="{{ $c->nombre }}" value="{{ $c->default }}">
	@else
		<div class="form-group">
			<label for="{{ $c->nombre }}" class="col-sm-2 control-label">{{ $c->nombre }}</label>
			<div class="col-sm-10">
				<div class="alert alert-danger" role="alert"> Tipo de campo incorrecto. </div>
			</div>
		</div>
	@endif

@endforeach


<input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />

<!-- SAVE -->
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		@if( $gestor->con_categoria === 0 || count($gestor->subcategorias) )
			<button type="submit" class="btn btn-primary">Guardar cambios</button>
		@else
			<button type="submit" class="btn btn-primary" disabled="disabled">Guardar cambios</button>
		@endif
		<a class="btn btn-default" href="{{ route('modulo',$id_modulo) }}">Volver</a>
	</div>
</div>

funcei/resources/views/admin/fields_static_alta.blade.php
@if( $gestor->con_formato > 0 )
	<!-- FORMATO -->
	<div class="form-group">
		<label for="formato" class="col-sm-2 control-label"> Formato </label>
		<div class="radio col-sm-offset-2 col-sm-10">
			@foreach( $formatos as $i => $formato )
			<label>
				<div class="thumbnail radioPreview">
					<img src="{{ asset('img/maqueta'.++$i.'.jpg') }}" alt="maqueta{{ $i }}" width="220" />
				</div>
				<input type="radio" name="formato" id="formato" value="{{ $i }}" checked="checked">
				Opción {{ $i }}
			</label>
			@endforeach
		</div>
	</div>
@endif

@if( $gestor->con_categoria > 0 )
	@if( count($gestor->subcategorias) )
		<!-- SUBCATEGORIAS -->
		<div class="form-group">
			<label for="id_subcategoria" class="col-sm-2 control-label"> Subcategoria </label>
			<div class="col-sm-10">
				<select class="form-control" name="id_subcategoria" id="id_subcategoria">
					@foreach( $gestor->subcategorias as $subcat )
						<option value="{{ $subcat->id }}">{{ $subcat->nombre }}</option>
					@endforeach
				</select>
			</div>
		</div>
	@else
		<div class="form-group">
			<label class="col-sm-2 control-label">Subcategoria</label>
			<div class="col-sm-10">
				<a class="btn btn-primary" href="{{ route('alta_subcategoria',array($id_modulo)) }}">Agregar Subcategoria</a>
				<div class="alert alert-danger" role="alert">No hay <b>subcategorias</b> creadas para asignarle a la publicación. Primero deberías crear alguna para <b>{{ $gestor->nombre }}</b>.</div>

			</div>
		</div>
	@endif
@endif


<input type="hidden" name="id_gestor" value="{{ $gestor->id }}">

funcei/resources/views/admin/fields_static_modificacion.blade.php
@if( $gestor->con_formato > 0 )
	<!-- FORMATO -->
	<div class="form-group">
		<label for="formato" class="col-sm-2 control-label"> Formato </label>
		<div class="radio col-sm-offset-2 col-sm-10">
			@if( ISSET($registro->formato) )
				@foreach( $formatos as $i => $formato )
				<label>
						<div class="thumbnail radioPreview">
							<img src="{{ asset('img/maqueta'.++$i.'.jpg') }}" alt="maqueta{{ $i }}" width="220" />
						</div>
						@if( intval($registro->formato) === $i )
							<input type="radio" name="formato" id="formato" name="formato" value="{{ $i }}" checked="checked">
						@else
						<input type="radio" name="formato" id="formato" name="formato" value="{{ $i }}">
						@endif
					<span>Opción {{ $i }}</span>
				</label>
				@endforeach
			@else
			<div class="alert alert-danger" role="alert">La tabla <b>contenido_{{ $gestor->contenido }}</b> no contiene un campo <b>"formato"</b> o esta mal escrito. </div>
			@endif
		</div>
	</div>
@endif


@if( $gestor->custom === 0 )
	<!-- CATEGOGIRAS (GESTORES) -->
	<div class="form-group">
		<label for="id_gestor" class="col-sm-2 control-label">Categoria</label>
		<div class="col-sm-10">
			<select class="form-control" name="id_gestor" id="id_gestor" data-gestor-id="{{ $gestor->id }}" data-api-url="{{ route('api.gestor.show',array('')) }}">
				@foreach( $gestoresHermanosPorModulo as $m )
					<optgroup label="{{ $m->nombre }}">
						@foreach( $m->gestores as $optionGestor )
							@if( $registro->id_gestor === $optionGestor->id )
								<option value="{{ $optionGestor->id }}" selected="selected">{{ $optionGestor->nombre }}</option>
							@else
								<option value="{{ $optionGestor->id }}">{{ $optionGestor->nombre }}</option>
							@endif
						@endforeach
					</optgroup>
				@endforeach
			</select>
		</div>
	</div>
@endif

@if( $gestor->con_categoria > 0 )
	@if( count($gestor->subcategorias) )
	<!-- SUBCATEGORIAS -->
	<div class="form-group">
		<label for="id_subcategoria" class="col-sm-2 control-label">Subcategoria</label>
		<div class="col-sm-10">
			<select class="form-control" name="id_subcategoria" id="id_subcategoria">
				@foreach( $gestor->subcategorias as $subcat )
					@if( $registro->id_subcategoria === $subcat->id )
						<option value="{{ $subcat->id }}" selected="selected">{{ $subcat->nombre }}</option>
					@else
						<option value="{{ $subcat->id }}">{{ $subcat->nombre }}</option>
					@endif
				@endforeach
			</select>
		</div>
	</div>
	@else
		<div class="form-group">
			<label class="col-sm-2 control-label">Subcategoria</label>
			<div class="col-sm-10">
				<a class="btn btn-primary" href="{{ route('alta_subcategoria',array($id_modulo)) }}">Agregar Subcategoria</a>
				<div class="alert alert-danger" role="alert">No hay <b>subcategorias</b> creadas para asignarle a la publicación. Primero deberías crear alguna para <b>{{ $gestor->nombre }}</b>.</div>

			</div>
		</div>
	@endif
@endif

funcei/resources/views/admin/modificacion.blade.php
@extends('app')

@section('admin_content')


<div class="row">

	@include('includes.admin_breadcrumb', array('accion' => 'modificar'))

	@include ('admin.sidebar')
	<div class="col-sm-offset-2 col-md-offset-2 col-sm-7 col-md-8 main">

    <h2>{{ $gestor->nombre }}</h2>
    <!-- FORM -->
    <form class="form-horizontal row" id="form_abm" method="POST" action="{{ route('do_modificacion_registro',array($id_modulo, $gestor->id, $gestor->contenido, $registro->id)) }}" enctype="multipart/form-data">

			@include ('admin.fields_static_modificacion')

			@include ('admin.fields')

    </form>
    <!-- END FORM -->

  </div>

</div>

@endsection